runtime: python39

entrypoint: gunicorn -w 4 -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "balmy-parser-423915-e7"
  DATASET_ID: "balmy-parser-423915-e7.customerdata"
  PORT: "80"

service: default  # Replace with your app's name

instance_class: F1  # You can adjust the instance class for memory/CPU needs

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
